//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountingEntities : DbContext
    {
        public AccountingEntities()
            : base("name=AccountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountingChart> AccountingCharts { get; set; }
        public virtual DbSet<ConsigneeAcc> ConsigneeAccs { get; set; }
        public virtual DbSet<CurrencyAcc> CurrencyAccs { get; set; }
        public virtual DbSet<HouseBillAcc> HouseBillAccs { get; set; }
        public virtual DbSet<ShipperAcc> ShipperAccs { get; set; }
        public virtual DbSet<PaymentTerm> PaymentTerms { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<AgentNote> AgentNotes { get; set; }
        public virtual DbSet<AccTransaction> AccTransactions { get; set; }
        public virtual DbSet<AccTransactionDetail> AccTransactionDetails { get; set; }
        public virtual DbSet<InvStatusLib> InvStatusLibs { get; set; }
        public virtual DbSet<InvoiceTotal> InvoiceTotals { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<CashInReceipt> CashInReceipts { get; set; }
        public virtual DbSet<CashInReceiptInv> CashInReceiptInvs { get; set; }
        public virtual DbSet<CashInReceiptCheck> CashInReceiptChecks { get; set; }
        public virtual DbSet<AgentNoteDetail> AgentNoteDetails { get; set; }
        public virtual DbSet<AgentNoteView> AgentNoteViews { get; set; }
        public virtual DbSet<CashInReceiptAgNote> CashInReceiptAgNotes { get; set; }
        public virtual DbSet<InvoiceTotalAP> InvoiceTotalAPs { get; set; }
        public virtual DbSet<CashOutReceipt> CashOutReceipts { get; set; }
        public virtual DbSet<CashOutReceiptAgNote> CashOutReceiptAgNotes { get; set; }
        public virtual DbSet<CashOutReceiptCheck> CashOutReceiptChecks { get; set; }
        public virtual DbSet<CashOutReceiptInv> CashOutReceiptInvs { get; set; }
        public virtual DbSet<CashOutCCCashDeposit> CashOutCCCashDeposits { get; set; }
        public virtual DbSet<InvoiceAP> InvoiceAPs { get; set; }
        public virtual DbSet<InvoiceDetailAP> InvoiceDetailAPs { get; set; }
        public virtual DbSet<APInvoiceView> APInvoiceViews { get; set; }
        public virtual DbSet<InvoiceView> InvoiceViews { get; set; }
        public virtual DbSet<CashInReceiptView> CashInReceiptViews { get; set; }
        public virtual DbSet<CashOutReceiptView> CashOutReceiptViews { get; set; }
        public virtual DbSet<ExpenseLib> ExpenseLibs { get; set; }
        public virtual DbSet<CashOutReceiptExpense> CashOutReceiptExpenses { get; set; }
        public virtual DbSet<AspNetUserAcc> AspNetUserAccs { get; set; }
        public virtual DbSet<ArCashDeposit> ArCashDeposits { get; set; }
        public virtual DbSet<ArCashDepositView> ArCashDepositViews { get; set; }
        public virtual DbSet<ArCashDepositBalance> ArCashDepositBalances { get; set; }
    }
}
