//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingChart
    {
        public AccountingChart()
        {
            this.AccountingChart1 = new HashSet<AccountingChart>();
            this.AccTransactionDetails = new HashSet<AccTransactionDetail>();
        }
    
        public string AccountId { get; set; }
        public string ParentAccountId { get; set; }
        public string AccountNameEn { get; set; }
        public string AccountNameAr { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<AccountingChart> AccountingChart1 { get; set; }
        public virtual AccountingChart AccountingChart2 { get; set; }
        public virtual ICollection<AccTransactionDetail> AccTransactionDetails { get; set; }
    }
}
