//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccTransactionDetail
    {
        public long TransDetailId { get; set; }
        public int TransId { get; set; }
        public string AccountId { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmount { get; set; }
        public int CurrencyId { get; set; }
    
        public virtual AccountingChart AccountingChart { get; set; }
        public virtual AccTransaction AccTransaction { get; set; }
        public virtual CurrencyAcc Currency { get; set; }
    }
}
