//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentNoteView
    {
        public int AgentNoteId { get; set; }
        public byte AgentNoteType { get; set; }
        public string AgentNoteCode { get; set; }
        public System.DateTime AgentNoteDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int AgentId { get; set; }
        public int OperationId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string Notes { get; set; }
        public string AgentNameEn { get; set; }
        public string AgentNameAr { get; set; }
        public byte OrderFrom { get; set; }
        public string OperationCode { get; set; }
        public string BookingNumber { get; set; }
        public string MBL { get; set; }
        public string InvStatusNameEn { get; set; }
        public string InvStatusNameAr { get; set; }
        public Nullable<byte> InvStatusId { get; set; }
        public decimal TotalAmount { get; set; }
        public int CurrencyId { get; set; }
        public string CurrencySign { get; set; }
        public string BankNameEn { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
    }
}
