//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentNoteDetail
    {
        public int AgentNoteDetailId { get; set; }
        public int AgentNoteId { get; set; }
        public int OperCostId { get; set; }
        public int OperCostLibId { get; set; }
        public decimal MainAmount { get; set; }
        public int MainCurrencyId { get; set; }
        public string MainCurrencySign { get; set; }
        public decimal ExchangeRate { get; set; }
        public decimal AgentNoteAmount { get; set; }
        public int CurrencyId { get; set; }
        public string CurrencySign { get; set; }
    
        public virtual AgentNote AgentNote { get; set; }
    }
}
