//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.AgentContacts = new HashSet<AgentContact>();
        }
    
        public int AgentId { get; set; }
        public string AgentCode { get; set; }
        public string AgentNameEn { get; set; }
        public string AgentNameAr { get; set; }
        public string AgentAddressEn { get; set; }
        public string AgentAddressAr { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string AccountId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<AgentContact> AgentContacts { get; set; }
    }
}
