//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentNote
    {
        public AgentNote()
        {
            this.AgentNoteDetails = new HashSet<AgentNoteDetail>();
            this.CashInReceiptAgNotes = new HashSet<CashInReceiptAgNote>();
            this.CashOutReceiptAgNotes = new HashSet<CashOutReceiptAgNote>();
        }
    
        public int AgentNoteId { get; set; }
        public byte AgentNoteType { get; set; }
        public string AgentNoteCode { get; set; }
        public System.DateTime AgentNoteDate { get; set; }
        public int AgentId { get; set; }
        public int OperationId { get; set; }
        public Nullable<int> HouseBillId { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public Nullable<int> ConsigneeId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string Notes { get; set; }
        public int BankAccId { get; set; }
        public int BankId { get; set; }
        public Nullable<int> TransId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<byte> InvStatusId { get; set; }
        public decimal TotalAmount { get; set; }
        public int CurrencyId { get; set; }
        public string CurrencySign { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual ConsigneeAcc Consignee { get; set; }
        public virtual ShipperAcc Shipper { get; set; }
        public virtual InvStatusLib InvStatusLib { get; set; }
        public virtual ICollection<AgentNoteDetail> AgentNoteDetails { get; set; }
        public virtual ICollection<CashInReceiptAgNote> CashInReceiptAgNotes { get; set; }
        public virtual ICollection<CashOutReceiptAgNote> CashOutReceiptAgNotes { get; set; }
    }
}
