//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.BankAccounts = new HashSet<BankAccount>();
            this.CashInReceipts = new HashSet<CashInReceipt>();
            this.CashOutReceipts = new HashSet<CashOutReceipt>();
        }
    
        public int BankId { get; set; }
        public string BankNameEn { get; set; }
        public string BankNameAr { get; set; }
        public string BankAddressEn { get; set; }
        public string BankAddressAr { get; set; }
        public string SwiftCode { get; set; }
        public string AccountId { get; set; }
    
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        public virtual ICollection<CashInReceipt> CashInReceipts { get; set; }
        public virtual ICollection<CashOutReceipt> CashOutReceipts { get; set; }
    }
}
