//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrierRateTransit
    {
        public int CarrierRateId { get; set; }
        public int TransitPortId { get; set; }
        public Nullable<int> TransitCountryId { get; set; }
    
        public virtual CarrierRate CarrierRate { get; set; }
        public virtual Port Port { get; set; }
    }
}
