//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrier
    {
        public Carrier()
        {
            this.CarrierContacts = new HashSet<CarrierContact>();
            this.CarrierRates = new HashSet<CarrierRate>();
            this.TruckingOrders = new HashSet<TruckingOrder>();
            this.Vessels = new HashSet<Vessel>();
        }
    
        public int CarrierId { get; set; }
        public string CarrierCode { get; set; }
        public string CarrierNameEn { get; set; }
        public string CarrierNameAr { get; set; }
        public string CarrierAddressEn { get; set; }
        public string CarrierAddressAr { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<byte> CarrierType { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string AccountId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<CarrierContact> CarrierContacts { get; set; }
        public virtual ICollection<CarrierRate> CarrierRates { get; set; }
        public virtual ICollection<TruckingOrder> TruckingOrders { get; set; }
        public virtual ICollection<Vessel> Vessels { get; set; }
    }
}
