//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashOutReceiptView
    {
        public int ReceiptId { get; set; }
        public string ReceiptCode { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public string CarrierNameEn { get; set; }
        public string CarrierNameAr { get; set; }
        public Nullable<int> ContractorId { get; set; }
        public string ContractorNameEn { get; set; }
        public string ContractorNameAr { get; set; }
        public Nullable<int> AgentId { get; set; }
        public string AgentNameEn { get; set; }
        public string AgentNameAr { get; set; }
        public byte PaymentTermId { get; set; }
        public string PaymentTermEn { get; set; }
        public string PaymentTermAr { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string Notes { get; set; }
        public decimal ReceiptAmount { get; set; }
        public Nullable<int> TransId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string CurrencySign { get; set; }
        public bool IsDeleted { get; set; }
        public string CheckNumber { get; set; }
        public System.DateTime CheckDueDate { get; set; }
        public bool IsCollected { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<System.DateTime> CollectDate { get; set; }
        public string CollectBy { get; set; }
        public string DeletedBy { get; set; }
        public string DeleteReason { get; set; }
        public Nullable<int> BankId { get; set; }
        public string UserName { get; set; }
    }
}
