//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Agents = new HashSet<Agent>();
            this.Carriers = new HashSet<Carrier>();
            this.Consignees = new HashSet<Consignee>();
            this.Contractors = new HashSet<Contractor>();
            this.Notifiers = new HashSet<Notifier>();
            this.Ports = new HashSet<Port>();
            this.Shippers = new HashSet<Shipper>();
            this.TruckingOrders = new HashSet<TruckingOrder>();
            this.TruckingOrders1 = new HashSet<TruckingOrder>();
            this.Areas = new HashSet<Area>();
            this.ContractorRates = new HashSet<ContractorRate>();
            this.ContractorRates1 = new HashSet<ContractorRate>();
        }
    
        public int CityId { get; set; }
        public int CountryId { get; set; }
        public string CityNameEn { get; set; }
        public string CityNameAr { get; set; }
    
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ICollection<Carrier> Carriers { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Consignee> Consignees { get; set; }
        public virtual ICollection<Contractor> Contractors { get; set; }
        public virtual ICollection<Notifier> Notifiers { get; set; }
        public virtual ICollection<Port> Ports { get; set; }
        public virtual ICollection<Shipper> Shippers { get; set; }
        public virtual ICollection<TruckingOrder> TruckingOrders { get; set; }
        public virtual ICollection<TruckingOrder> TruckingOrders1 { get; set; }
        public virtual ICollection<Area> Areas { get; set; }
        public virtual ICollection<ContractorRate> ContractorRates { get; set; }
        public virtual ICollection<ContractorRate> ContractorRates1 { get; set; }
    }
}
