//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsigneeAcc
    {
        public ConsigneeAcc()
        {
            this.HouseBills = new HashSet<HouseBillAcc>();
            this.Invoices = new HashSet<Invoice>();
            this.AgentNotes = new HashSet<AgentNote>();
            this.CashInReceipts = new HashSet<CashInReceipt>();
            this.ArCashDeposits = new HashSet<ArCashDeposit>();
            this.ArCashDepositBalances = new HashSet<ArCashDepositBalance>();
        }
    
        public int ConsigneeId { get; set; }
        public string ConsigneeCode { get; set; }
        public string ConsigneeNameEn { get; set; }
        public string ConsigneeNameAr { get; set; }
        public string ConsigneeAddressEn { get; set; }
        public string ConsigneeAddressAr { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string AccountId { get; set; }
        public string TaxDepositAccountId { get; set; }
        public string VatTaxAccountId { get; set; }
    
        public virtual ICollection<HouseBillAcc> HouseBills { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<AgentNote> AgentNotes { get; set; }
        public virtual ICollection<CashInReceipt> CashInReceipts { get; set; }
        public virtual ICollection<ArCashDeposit> ArCashDeposits { get; set; }
        public virtual ICollection<ArCashDepositBalance> ArCashDepositBalances { get; set; }
    }
}
