//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignee
    {
        public Consignee()
        {
            this.ConsigneeContacts = new HashSet<ConsigneeContact>();
            this.Notifiers = new HashSet<Notifier>();
            this.TruckingOrders = new HashSet<TruckingOrder>();
        }
    
        public int ConsigneeId { get; set; }
        public string ConsigneeCode { get; set; }
        public string ConsigneeNameEn { get; set; }
        public string ConsigneeNameAr { get; set; }
        public string ConsigneeAddressEn { get; set; }
        public string ConsigneeAddressAr { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string AccountId { get; set; }
        public string TaxDepositAccountId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<ConsigneeContact> ConsigneeContacts { get; set; }
        public virtual ICollection<Notifier> Notifiers { get; set; }
        public virtual ICollection<TruckingOrder> TruckingOrders { get; set; }
    }
}
