//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        public Contractor()
        {
            this.ContractorContacts = new HashSet<ContractorContact>();
            this.TruckingOrderDetails = new HashSet<TruckingOrderDetail>();
            this.ContractorRates = new HashSet<ContractorRate>();
        }
    
        public int ContractorId { get; set; }
        public string ContractorCode { get; set; }
        public string ContractorNameEn { get; set; }
        public string ContractorNameAr { get; set; }
        public string ContractorAddressEn { get; set; }
        public string ContractorAddressAr { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string AccountId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<ContractorContact> ContractorContacts { get; set; }
        public virtual ICollection<TruckingOrderDetail> TruckingOrderDetails { get; set; }
        public virtual ICollection<ContractorRate> ContractorRates { get; set; }
    }
}
