//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorRate
    {
        public int ContractorRateId { get; set; }
        public int ContractorId { get; set; }
        public Nullable<int> FromAreaId { get; set; }
        public Nullable<int> ToAreaId { get; set; }
        public int FromCityId { get; set; }
        public int ToCityId { get; set; }
        public int ContainerTypeId { get; set; }
        public decimal CostAmount { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<bool> ValidToChecked { get; set; }
        public Nullable<System.DateTime> ValidToDate { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Area Area1 { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual ContainerType ContainerType { get; set; }
        public virtual Contractor Contractor { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
