//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.CarrierRates = new HashSet<CarrierRate>();
            this.CarrierRates1 = new HashSet<CarrierRate>();
            this.CurrencyExchages = new HashSet<CurrencyExchage>();
            this.CurrencyExchages1 = new HashSet<CurrencyExchage>();
            this.TruckingOrderCosts = new HashSet<TruckingOrderCost>();
            this.ContractorRates = new HashSet<ContractorRate>();
        }
    
        public int CurrencyId { get; set; }
        public string CurrencySign { get; set; }
        public string CurrencyName { get; set; }
        public string AccountId { get; set; }
    
        public virtual ICollection<CarrierRate> CarrierRates { get; set; }
        public virtual ICollection<CarrierRate> CarrierRates1 { get; set; }
        public virtual ICollection<CurrencyExchage> CurrencyExchages { get; set; }
        public virtual ICollection<CurrencyExchage> CurrencyExchages1 { get; set; }
        public virtual ICollection<TruckingOrderCost> TruckingOrderCosts { get; set; }
        public virtual ICollection<ContractorRate> ContractorRates { get; set; }
    }
}
