//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyOper
    {
        public CurrencyOper()
        {
            this.CustomClearanceDetails = new HashSet<CustomClearanceDetail>();
            this.HouseBills = new HashSet<HouseBill>();
            this.HouseBills1 = new HashSet<HouseBill>();
            this.Operations = new HashSet<Operation>();
            this.Operations1 = new HashSet<Operation>();
            this.OperationCosts = new HashSet<OperationCost>();
            this.Quotations = new HashSet<Quotation>();
            this.Quotations1 = new HashSet<Quotation>();
            this.Quotations2 = new HashSet<Quotation>();
            this.Quotations3 = new HashSet<Quotation>();
            this.Operations2 = new HashSet<Operation>();
            this.OperationCosts1 = new HashSet<OperationCost>();
        }
    
        public int CurrencyId { get; set; }
        public string CurrencySign { get; set; }
        public string CurrencyName { get; set; }
        public string AccountId { get; set; }
    
        public virtual ICollection<CustomClearanceDetail> CustomClearanceDetails { get; set; }
        public virtual ICollection<HouseBill> HouseBills { get; set; }
        public virtual ICollection<HouseBill> HouseBills1 { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ICollection<Operation> Operations1 { get; set; }
        public virtual ICollection<OperationCost> OperationCosts { get; set; }
        public virtual ICollection<Quotation> Quotations { get; set; }
        public virtual ICollection<Quotation> Quotations1 { get; set; }
        public virtual ICollection<Quotation> Quotations2 { get; set; }
        public virtual ICollection<Quotation> Quotations3 { get; set; }
        public virtual ICollection<Operation> Operations2 { get; set; }
        public virtual ICollection<OperationCost> OperationCosts1 { get; set; }
    }
}
