//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomClearanceOrder
    {
        public CustomClearanceOrder()
        {
            this.CustomClearanceDetails = new HashSet<CustomClearanceDetail>();
        }
    
        public int CCId { get; set; }
        public int OperationId { get; set; }
        public int HouseBillId { get; set; }
        public System.DateTime NeedArriveDate { get; set; }
        public System.TimeSpan NeedArriveTime { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public byte StatusId { get; set; }
        public string AssignToUserId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CustomReleaseId { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<CustomClearanceDetail> CustomClearanceDetails { get; set; }
        public virtual HouseBill HouseBill { get; set; }
        public virtual Operation Operation { get; set; }
    }
}
