//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomClearanceDetail
    {
        public int CCDetailsId { get; set; }
        public int CCId { get; set; }
        public int CCCostId { get; set; }
        public decimal CCCostNet { get; set; }
        public decimal CCCostSelling { get; set; }
        public int CurrencyId { get; set; }
    
        public virtual CustomClearanceOrder CustomClearanceOrder { get; set; }
        public virtual CurrencyOper Currency { get; set; }
        public virtual CustomClearanceCostLib CustomClearanceCostLib { get; set; }
    }
}
