//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomClearanceCostLib
    {
        public CustomClearanceCostLib()
        {
            this.CustomClearanceDetails = new HashSet<CustomClearanceDetail>();
        }
    
        public int CCCostId { get; set; }
        public string CostNameEn { get; set; }
        public string CostNameAr { get; set; }
    
        public virtual ICollection<CustomClearanceDetail> CustomClearanceDetails { get; set; }
    }
}
