//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseLib
    {
        public ExpenseLib()
        {
            this.CashOutReceiptExpenses = new HashSet<CashOutReceiptExpense>();
        }
    
        public int ExpenseId { get; set; }
        public string ExpenseNameEn { get; set; }
        public string ExpenseNameAr { get; set; }
        public string AccountId { get; set; }
    
        public virtual ICollection<CashOutReceiptExpense> CashOutReceiptExpenses { get; set; }
    }
}
