//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseBillView
    {
        public int HouseBillId { get; set; }
        public byte OrderFrom { get; set; }
        public int OperationId { get; set; }
        public string OperationCode { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public string HouseBL { get; set; }
        public int FromPortId { get; set; }
        public string FromPort { get; set; }
        public int ToPortId { get; set; }
        public string ToPort { get; set; }
        public int ShipperId { get; set; }
        public string ShipperNameEn { get; set; }
        public int ConsigneeId { get; set; }
        public string ConsigneeNameEn { get; set; }
        public Nullable<int> NotifierId { get; set; }
        public string NotifierNameEn { get; set; }
        public Nullable<bool> NotifierAsConsignee { get; set; }
        public byte DeliveryType { get; set; }
        public Nullable<int> AgentId { get; set; }
        public string AgentNameEn { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<int> NumberOfPackages { get; set; }
        public Nullable<bool> IsPrepaid { get; set; }
        public Nullable<decimal> CollectedFreightCost { get; set; }
        public Nullable<int> FreighCurrencyId { get; set; }
        public string FreighCurrency { get; set; }
        public Nullable<decimal> CollectedThcCost { get; set; }
        public Nullable<int> ThcCurrencyId { get; set; }
        public string ThcCurrency { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string GoodsDescription { get; set; }
        public string Marks { get; set; }
        public byte StatusId { get; set; }
        public string StatusName { get; set; }
        public string BookingNumber { get; set; }
        public string VesselName { get; set; }
        public string IncotermName { get; set; }
        public Nullable<System.DateTime> DateOfDeparture { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public byte CarrierType { get; set; }
        public string MBL { get; set; }
        public string CarrierNameEn { get; set; }
        public int CarrierId { get; set; }
        public Nullable<int> VesselId { get; set; }
        public string ConsigneeAddressEn { get; set; }
        public string ConsigneePhoneNumber { get; set; }
        public string ConsigneeFaxNumber { get; set; }
        public string NotifierAddressEn { get; set; }
        public string NotifierPhoneNumber { get; set; }
        public string NotifierFaxNumber { get; set; }
        public string AgentAddressEn { get; set; }
        public string AgentPhoneNumber { get; set; }
        public string AgentFaxNumber { get; set; }
        public string FlightNumber { get; set; }
        public string PackageTypeNameEn { get; set; }
    }
}
