//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceTotals = new HashSet<InvoiceTotal>();
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.CashInReceiptInvs = new HashSet<CashInReceiptInv>();
            this.CashOutReceiptInvs = new HashSet<CashOutReceiptInv>();
        }
    
        public int InvoiceId { get; set; }
        public string InvoiceCode { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int OperationId { get; set; }
        public int HouseBillId { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public Nullable<int> ConsigneeId { get; set; }
        public byte OrderFrom { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string Notes { get; set; }
        public byte PaymentTermId { get; set; }
        public byte InvoiceType { get; set; }
        public Nullable<int> TransId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<byte> InvStatusId { get; set; }
        public int InvCurrencyId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public string DeleteReason { get; set; }
    
        public virtual ConsigneeAcc Consignee { get; set; }
        public virtual HouseBillAcc HouseBill { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual ShipperAcc Shipper { get; set; }
        public virtual InvStatusLib InvStatusLib { get; set; }
        public virtual AccTransaction AccTransaction { get; set; }
        public virtual ICollection<InvoiceTotal> InvoiceTotals { get; set; }
        public virtual CurrencyAcc Currency { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual ICollection<CashInReceiptInv> CashInReceiptInvs { get; set; }
        public virtual ICollection<CashOutReceiptInv> CashOutReceiptInvs { get; set; }
    }
}
