//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceView
    {
        public int InvoiceId { get; set; }
        public string InvoiceCode { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int OperationId { get; set; }
        public int HouseBillId { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public Nullable<int> ConsigneeId { get; set; }
        public byte OrderFrom { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string Notes { get; set; }
        public byte PaymentTermId { get; set; }
        public byte InvoiceType { get; set; }
        public Nullable<byte> InvStatusId { get; set; }
        public string PaymentTermEn { get; set; }
        public string ConsigneeNameEn { get; set; }
        public string ShipperNameEn { get; set; }
        public int CurrencyId { get; set; }
        public string CurrencySign { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> TransId { get; set; }
        public string InvStatusNameEn { get; set; }
        public string InvStatusNameAr { get; set; }
        public string ShipperNameAr { get; set; }
        public string ConsigneeNameAr { get; set; }
        public string PaymentTermAr { get; set; }
        public int InvCurrencyId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public string DeleteReason { get; set; }
        public string OperationCode { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public string HouseBL { get; set; }
        public decimal TaxDepositAmount { get; set; }
        public decimal TotalBeforeTax { get; set; }
    }
}
