//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public long InvDetailId { get; set; }
        public int InvoiceId { get; set; }
        public int CostFkId { get; set; }
        public byte FkType { get; set; }
        public decimal MainAmount { get; set; }
        public decimal InvoiceAmount { get; set; }
        public int CurrencyId { get; set; }
        public int MainCurrencyId { get; set; }
        public decimal ExchangeRate { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public string PrintedTitle { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual CurrencyAcc InvCurr { get; set; }
        public virtual CurrencyAcc MainCurr { get; set; }
    }
}
