//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceAP
    {
        public InvoiceAP()
        {
            this.CashOutReceiptInvs = new HashSet<CashOutReceiptInv>();
            this.InvoiceDetailAPs = new HashSet<InvoiceDetailAP>();
            this.InvoiceTotalAPs = new HashSet<InvoiceTotalAP>();
        }
    
        public int InvoiceId { get; set; }
        public string InvoiceCode { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string APInvoiceCode { get; set; }
        public int OperationId { get; set; }
        public Nullable<int> HouseBillId { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public Nullable<int> ContractorId { get; set; }
        public byte OrderFrom { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string Notes { get; set; }
        public byte PaymentTermId { get; set; }
        public Nullable<byte> InvStatusId { get; set; }
        public Nullable<int> TransId { get; set; }
        public int InvCurrencyId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public string DeleteReason { get; set; }
        public byte InvoiceType { get; set; }
    
        public virtual ICollection<CashOutReceiptInv> CashOutReceiptInvs { get; set; }
        public virtual CurrencyAcc Currency { get; set; }
        public virtual HouseBillAcc HouseBill { get; set; }
        public virtual InvStatusLib InvStatusLib { get; set; }
        public virtual PaymentTerm PaymentTerm { get; set; }
        public virtual ICollection<InvoiceDetailAP> InvoiceDetailAPs { get; set; }
        public virtual ICollection<InvoiceTotalAP> InvoiceTotalAPs { get; set; }
    }
}
