//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvStatusLib
    {
        public InvStatusLib()
        {
            this.AgentNotes = new HashSet<AgentNote>();
            this.Invoices = new HashSet<Invoice>();
            this.InvoiceAPs = new HashSet<InvoiceAP>();
        }
    
        public byte InvStatusId { get; set; }
        public string InvStatusNameEn { get; set; }
        public string InvStatusNameAr { get; set; }
    
        public virtual ICollection<AgentNote> AgentNotes { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<InvoiceAP> InvoiceAPs { get; set; }
    }
}
