//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationCostLib
    {
        public OperationCostLib()
        {
            this.OperationCosts = new HashSet<OperationCost>();
        }
    
        public int OperCostLibId { get; set; }
        public string OperCostNameEn { get; set; }
        public string OperCostNameAr { get; set; }
    
        public virtual ICollection<OperationCost> OperationCosts { get; set; }
    }
}
