//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationCost
    {
        public int OperCostId { get; set; }
        public int HouseBillId { get; set; }
        public int OperCostLibId { get; set; }
        public int OperationId { get; set; }
        public decimal OperationCostNet { get; set; }
        public decimal OperationCostSelling { get; set; }
        public int CurrencyId { get; set; }
        public bool IsAgentCost { get; set; }
        public Nullable<int> CurrencyIdSelling { get; set; }
        public Nullable<bool> IsAccounting { get; set; }
    
        public virtual HouseBill HouseBill { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual OperationCostLib OperationCostLib { get; set; }
        public virtual CurrencyOper Currency { get; set; }
        public virtual CurrencyOper Currency1 { get; set; }
    }
}
