//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageType
    {
        public int PackageTypeId { get; set; }
        public string PackageTypeNameEn { get; set; }
        public string PackageTypeNameAr { get; set; }
    }
}
