//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTerm
    {
        public PaymentTerm()
        {
            this.Invoices = new HashSet<Invoice>();
            this.CashInReceipts = new HashSet<CashInReceipt>();
            this.CashOutReceipts = new HashSet<CashOutReceipt>();
            this.InvoiceAPs = new HashSet<InvoiceAP>();
            this.ArCashDeposits = new HashSet<ArCashDeposit>();
        }
    
        public byte PaymentTermId { get; set; }
        public string PaymentTermEn { get; set; }
        public string PaymentTermAr { get; set; }
    
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<CashInReceipt> CashInReceipts { get; set; }
        public virtual ICollection<CashOutReceipt> CashOutReceipts { get; set; }
        public virtual ICollection<InvoiceAP> InvoiceAPs { get; set; }
        public virtual ICollection<ArCashDeposit> ArCashDeposits { get; set; }
    }
}
