//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Port
    {
        public Port()
        {
            this.CarrierRates = new HashSet<CarrierRate>();
            this.CarrierRates1 = new HashSet<CarrierRate>();
            this.CarrierRateTransits = new HashSet<CarrierRateTransit>();
        }
    
        public int PortId { get; set; }
        public int CountryId { get; set; }
        public int CityId { get; set; }
        public byte PortType { get; set; }
        public string PortNameEn { get; set; }
        public string PortNameAr { get; set; }
    
        public virtual ICollection<CarrierRate> CarrierRates { get; set; }
        public virtual ICollection<CarrierRate> CarrierRates1 { get; set; }
        public virtual ICollection<CarrierRateTransit> CarrierRateTransits { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
    }
}
