//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationContainer
    {
        public int QuoteId { get; set; }
        public int ContainerTypeId { get; set; }
        public byte NumberOfContainers { get; set; }
    
        public virtual Quotation Quotation { get; set; }
    }
}
