//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public Shipper()
        {
            this.ShipperContacts = new HashSet<ShipperContact>();
            this.TruckingOrders = new HashSet<TruckingOrder>();
        }
    
        public int ShipperId { get; set; }
        public string ShipperCode { get; set; }
        public string ShipperNameEn { get; set; }
        public string ShipperNameAr { get; set; }
        public string ShipperAddressEn { get; set; }
        public string ShipperAddressAr { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string AccountId { get; set; }
        public string TaxDepositAccountId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<ShipperContact> ShipperContacts { get; set; }
        public virtual ICollection<TruckingOrder> TruckingOrders { get; set; }
    }
}
