//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusLibOper
    {
        public StatusLibOper()
        {
            this.HouseBills = new HashSet<HouseBill>();
            this.Operations = new HashSet<Operation>();
            this.Quotations = new HashSet<Quotation>();
        }
    
        public byte StatusId { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<HouseBill> HouseBills { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public virtual ICollection<Quotation> Quotations { get; set; }
    }
}
