//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusLib
    {
        public StatusLib()
        {
            this.TruckingOrders = new HashSet<TruckingOrder>();
        }
    
        public byte StatusId { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<TruckingOrder> TruckingOrders { get; set; }
    }
}
