//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticTextLabel
    {
        public int LblId { get; set; }
        public int StaticTextId { get; set; }
        public string FieldPrefix { get; set; }
        public string TextEn { get; set; }
        public string TextAr { get; set; }
    
        public virtual StaticText StaticText { get; set; }
    }
}
