//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSetup
    {
        public int CompanyId { get; set; }
        public string CarrierPrefix { get; set; }
        public string ShipperPrefix { get; set; }
        public string ConsigneePrefix { get; set; }
        public string NotifierPrefix { get; set; }
        public string ContractorPrefix { get; set; }
        public Nullable<int> DefaultCurrencyId { get; set; }
        public string ImportPrefix { get; set; }
        public string ExportPrefix { get; set; }
    }
}
