//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckingOrder
    {
        public int TruckingOrderId { get; set; }
        public string TruckingOrderCode { get; set; }
        public int OperationId { get; set; }
        public byte OrderFrom { get; set; }
        public Nullable<int> HouseBillId { get; set; }
        public string OperationCode { get; set; }
        public string HouseBL { get; set; }
        public string BookingNo { get; set; }
        public int FromAreaId { get; set; }
        public int ToAreaId { get; set; }
        public Nullable<int> FromCityId { get; set; }
        public Nullable<int> ToCityId { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public Nullable<int> ConsigneeId { get; set; }
        public System.DateTime NeedArriveDate { get; set; }
        public System.TimeSpan NeedArriveTime { get; set; }
        public string ShipFromAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public byte StatusId { get; set; }
        public string AssignToUserId { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Consignee Consignee { get; set; }
        public virtual Shipper Shipper { get; set; }
        public virtual StatusLib StatusLib { get; set; }
        public virtual TruckingOrderDetail TruckingOrderDetail { get; set; }
    }
}
