//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckingOrdersView
    {
        public int TruckingOrderId { get; set; }
        public string TruckingOrderCode { get; set; }
        public int OperationId { get; set; }
        public string OperationCode { get; set; }
        public byte OrderFrom { get; set; }
        public string BookingNo { get; set; }
        public string ShipperNameEn { get; set; }
        public string ConsigneeNameEn { get; set; }
        public string CarrierNameEn { get; set; }
        public string FromAreaName { get; set; }
        public string ToAreaName { get; set; }
        public string FromCityName { get; set; }
        public string ToCityName { get; set; }
        public System.DateTime NeedArriveDate { get; set; }
        public System.TimeSpan NeedArriveTime { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ContractorNameEn { get; set; }
        public string DriverName { get; set; }
        public string DriverMobile { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public Nullable<System.TimeSpan> ArriveTime { get; set; }
        public Nullable<System.DateTime> LoadedDate { get; set; }
        public Nullable<System.TimeSpan> LoadedTime { get; set; }
        public string Notes { get; set; }
        public string StatusName { get; set; }
        public string CreateBy { get; set; }
        public byte StatusId { get; set; }
        public string AssignToUserId { get; set; }
        public int FromAreaId { get; set; }
        public int ToAreaId { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public Nullable<int> ConsigneeId { get; set; }
        public Nullable<int> FromCityId { get; set; }
        public Nullable<int> ToCityId { get; set; }
        public Nullable<int> ContractorId { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<System.TimeSpan> LeaveTime { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string FollowUpBy { get; set; }
        public Nullable<int> CostCurrencyId { get; set; }
        public string ShipFromAddress { get; set; }
        public Nullable<int> HouseBillId { get; set; }
        public string HouseBL { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
    }
}
