//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckingOrderDetail
    {
        public TruckingOrderDetail()
        {
            this.TruckingOrderCosts = new HashSet<TruckingOrderCost>();
        }
    
        public int TruckingOrderId { get; set; }
        public int ContractorId { get; set; }
        public string TruckingOrderCode { get; set; }
        public string DriverName { get; set; }
        public string DriverMobile { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public Nullable<System.TimeSpan> ArriveTime { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<System.TimeSpan> LeaveTime { get; set; }
        public Nullable<System.DateTime> LoadedDate { get; set; }
        public Nullable<System.TimeSpan> LoadedTime { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string FollowUpBy { get; set; }
        public Nullable<int> CostCurrencyId { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual ICollection<TruckingOrderCost> TruckingOrderCosts { get; set; }
        public virtual TruckingOrder TruckingOrder { get; set; }
    }
}
