//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vessel
    {
        public int VesselId { get; set; }
        public string VesselName { get; set; }
        public Nullable<int> CarrierId { get; set; }
    
        public virtual Carrier Carrier { get; set; }
    }
}
