//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.ModuleScreens = new HashSet<ModuleScreen>();
        }
    
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string ModuleNameAr { get; set; }
    
        public virtual ICollection<ModuleScreen> ModuleScreens { get; set; }
    }
}
