//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenActionDep
    {
        public int ScreenId { get; set; }
        public int ActionId { get; set; }
        public int DepId { get; set; }
        public string TempCol { get; set; }
    
        public virtual ModuleScreen ModuleScreen { get; set; }
        public virtual SecActionLib SecActionLib { get; set; }
    }
}
