//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecActionLib
    {
        public SecActionLib()
        {
            this.ScreenActions = new HashSet<ScreenAction>();
            this.ScreenActionDeps = new HashSet<ScreenActionDep>();
            this.ScreenActionUsers = new HashSet<ScreenActionUser>();
        }
    
        public int ActionId { get; set; }
        public string ActionName { get; set; }
        public string ActionNameAr { get; set; }
    
        public virtual ICollection<ScreenAction> ScreenActions { get; set; }
        public virtual ICollection<ScreenActionDep> ScreenActionDeps { get; set; }
        public virtual ICollection<ScreenActionUser> ScreenActionUsers { get; set; }
    }
}
