//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFreight.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SetupEntities : DbContext
    {
        public SetupEntities()
            : base("name=SetupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PrefixSetup> PrefixSetups { get; set; }
        public virtual DbSet<PrefixLastId> PrefixLastIds { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleScreen> ModuleScreens { get; set; }
        public virtual DbSet<ScreenAction> ScreenActions { get; set; }
        public virtual DbSet<ScreenActionDep> ScreenActionDeps { get; set; }
        public virtual DbSet<ScreenActionUser> ScreenActionUsers { get; set; }
        public virtual DbSet<SecActionLib> SecActionLibs { get; set; }
        public virtual DbSet<UserEmployee> UserEmployees { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
    }
}
